/**
 *
 * $Id$
 */
package pagos.validation;

import org.eclipse.emf.common.util.EList;

import pagos.IfBlock;
import pagos.ReturnBlock;

/**
 * A sample validator interface for {@link pagos.Formula}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormulaValidator {
	boolean validate();

	boolean validateFormulaBody(EList<IfBlock> value);
	boolean validateFormulaReturn(ReturnBlock value);
}
