/**
 *
 * $Id$
 */
package pagos.validation;

import pagos.ElseSegment;
import pagos.IfCondition;

/**
 * A sample validator interface for {@link pagos.IfBlock}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfBlockValidator {
	boolean validate();

	boolean validateIfSentence(IfCondition value);
	boolean validateElseSentence(ElseSegment value);
}
