/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos.impl;

import co.edu.uniandes.pagos.EntityAttribute;
import co.edu.uniandes.pagos.PagosPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Entity Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EntityAttributeImpl extends CalculationAttributeImpl implements EntityAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EntityAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PagosPackage.Literals.ENTITY_ATTRIBUTE;
  }

} //EntityAttributeImpl
