/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos.impl;

import co.edu.uniandes.pagos.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PagosFactoryImpl extends EFactoryImpl implements PagosFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PagosFactory init()
  {
    try
    {
      PagosFactory thePagosFactory = (PagosFactory)EPackage.Registry.INSTANCE.getEFactory(PagosPackage.eNS_URI);
      if (thePagosFactory != null)
      {
        return thePagosFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PagosFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PagosFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PagosPackage.APPLICATION: return createApplication();
      case PagosPackage.INTERMEDIARY: return createIntermediary();
      case PagosPackage.SUPER_ENTITY: return createSuperEntity();
      case PagosPackage.PARTICIPANT: return createParticipant();
      case PagosPackage.PROVIDER: return createProvider();
      case PagosPackage.INFORMATION_TEMPLATE: return createInformationTemplate();
      case PagosPackage.CALCULATION_TEMPLATE: return createCalculationTemplate();
      case PagosPackage.FORMULA: return createFormula();
      case PagosPackage.EXPRESION_LOGICA: return createExpresionLogica();
      case PagosPackage.EXPRESSION: return createExpression();
      case PagosPackage.SUPER_ENTITY_ATTRIBUTE: return createSuperEntityAttribute();
      case PagosPackage.ENTITY_ATTRIBUTE: return createEntityAttribute();
      case PagosPackage.FORM_ATTRIBUTE: return createFormAttribute();
      case PagosPackage.VARIABLE_ATTRIBUTE: return createVariableAttribute();
      case PagosPackage.CALCULATION_ATTRIBUTE: return createCalculationAttribute();
      case PagosPackage.TERMINAL_VALUE: return createTerminalValue();
      case PagosPackage.MATH_ADD: return createmathADD();
      case PagosPackage.MATH_MULT: return createmathMULT();
      case PagosPackage.ADICION: return createAdicion();
      case PagosPackage.MULTIPLICACION: return createMultiplicacion();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Application createApplication()
  {
    ApplicationImpl application = new ApplicationImpl();
    return application;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Intermediary createIntermediary()
  {
    IntermediaryImpl intermediary = new IntermediaryImpl();
    return intermediary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SuperEntity createSuperEntity()
  {
    SuperEntityImpl superEntity = new SuperEntityImpl();
    return superEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Participant createParticipant()
  {
    ParticipantImpl participant = new ParticipantImpl();
    return participant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Provider createProvider()
  {
    ProviderImpl provider = new ProviderImpl();
    return provider;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InformationTemplate createInformationTemplate()
  {
    InformationTemplateImpl informationTemplate = new InformationTemplateImpl();
    return informationTemplate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CalculationTemplate createCalculationTemplate()
  {
    CalculationTemplateImpl calculationTemplate = new CalculationTemplateImpl();
    return calculationTemplate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Formula createFormula()
  {
    FormulaImpl formula = new FormulaImpl();
    return formula;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExpresionLogica createExpresionLogica()
  {
    ExpresionLogicaImpl expresionLogica = new ExpresionLogicaImpl();
    return expresionLogica;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SuperEntityAttribute createSuperEntityAttribute()
  {
    SuperEntityAttributeImpl superEntityAttribute = new SuperEntityAttributeImpl();
    return superEntityAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EntityAttribute createEntityAttribute()
  {
    EntityAttributeImpl entityAttribute = new EntityAttributeImpl();
    return entityAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FormAttribute createFormAttribute()
  {
    FormAttributeImpl formAttribute = new FormAttributeImpl();
    return formAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VariableAttribute createVariableAttribute()
  {
    VariableAttributeImpl variableAttribute = new VariableAttributeImpl();
    return variableAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CalculationAttribute createCalculationAttribute()
  {
    CalculationAttributeImpl calculationAttribute = new CalculationAttributeImpl();
    return calculationAttribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TerminalValue createTerminalValue()
  {
    TerminalValueImpl terminalValue = new TerminalValueImpl();
    return terminalValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public mathADD createmathADD()
  {
    mathADDImpl mathADD = new mathADDImpl();
    return mathADD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public mathMULT createmathMULT()
  {
    mathMULTImpl mathMULT = new mathMULTImpl();
    return mathMULT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Adicion createAdicion()
  {
    AdicionImpl adicion = new AdicionImpl();
    return adicion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Multiplicacion createMultiplicacion()
  {
    MultiplicacionImpl multiplicacion = new MultiplicacionImpl();
    return multiplicacion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PagosPackage getPagosPackage()
  {
    return (PagosPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PagosPackage getPackage()
  {
    return PagosPackage.eINSTANCE;
  }

} //PagosFactoryImpl
