/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.gramaticaPayments.ui.internal.GramaticaPaymentsActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PagosExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GramaticaPaymentsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GramaticaPaymentsActivator.getInstance().getInjector(GramaticaPaymentsActivator.CO_EDU_UNIANDES_PAGOS);
	}
	
}
