/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.pagos.FormAttribute#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see co.edu.uniandes.pagos.PagosPackage#getFormAttribute()
 * @model
 * @generated
 */
public interface FormAttribute extends CalculationAttribute
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see co.edu.uniandes.pagos.PagosPackage#getFormAttribute_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link co.edu.uniandes.pagos.FormAttribute#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // FormAttribute
