/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Entity Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.edu.uniandes.pagos.PagosPackage#getSuperEntityAttribute()
 * @model
 * @generated
 */
public interface SuperEntityAttribute extends CalculationAttribute
{
} // SuperEntityAttribute
