/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos.impl;

import co.edu.uniandes.pagos.ExpresionLogica;
import co.edu.uniandes.pagos.IfCondition;
import co.edu.uniandes.pagos.PagosPackage;
import co.edu.uniandes.pagos.ReturnBlock;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>If Condition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.pagos.impl.IfConditionImpl#getLogExp <em>Log Exp</em>}</li>
 *   <li>{@link co.edu.uniandes.pagos.impl.IfConditionImpl#getFormulaReturn <em>Formula Return</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IfConditionImpl extends MinimalEObjectImpl.Container implements IfCondition
{
  /**
	 * The cached value of the '{@link #getLogExp() <em>Log Exp</em>}' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getLogExp()
	 * @generated
	 * @ordered
	 */
  protected EList<ExpresionLogica> logExp;

  /**
	 * The cached value of the '{@link #getFormulaReturn() <em>Formula Return</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getFormulaReturn()
	 * @generated
	 * @ordered
	 */
  protected ReturnBlock formulaReturn;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected IfConditionImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return PagosPackage.Literals.IF_CONDITION;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EList<ExpresionLogica> getLogExp()
  {
		if (logExp == null) {
			logExp = new EObjectContainmentEList<ExpresionLogica>(ExpresionLogica.class, this, PagosPackage.IF_CONDITION__LOG_EXP);
		}
		return logExp;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ReturnBlock getFormulaReturn()
  {
		return formulaReturn;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public NotificationChain basicSetFormulaReturn(ReturnBlock newFormulaReturn, NotificationChain msgs)
  {
		ReturnBlock oldFormulaReturn = formulaReturn;
		formulaReturn = newFormulaReturn;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PagosPackage.IF_CONDITION__FORMULA_RETURN, oldFormulaReturn, newFormulaReturn);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setFormulaReturn(ReturnBlock newFormulaReturn)
  {
		if (newFormulaReturn != formulaReturn) {
			NotificationChain msgs = null;
			if (formulaReturn != null)
				msgs = ((InternalEObject)formulaReturn).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PagosPackage.IF_CONDITION__FORMULA_RETURN, null, msgs);
			if (newFormulaReturn != null)
				msgs = ((InternalEObject)newFormulaReturn).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PagosPackage.IF_CONDITION__FORMULA_RETURN, null, msgs);
			msgs = basicSetFormulaReturn(newFormulaReturn, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, PagosPackage.IF_CONDITION__FORMULA_RETURN, newFormulaReturn, newFormulaReturn));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
		switch (featureID) {
			case PagosPackage.IF_CONDITION__LOG_EXP:
				return ((InternalEList<?>)getLogExp()).basicRemove(otherEnd, msgs);
			case PagosPackage.IF_CONDITION__FORMULA_RETURN:
				return basicSetFormulaReturn(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case PagosPackage.IF_CONDITION__LOG_EXP:
				return getLogExp();
			case PagosPackage.IF_CONDITION__FORMULA_RETURN:
				return getFormulaReturn();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case PagosPackage.IF_CONDITION__LOG_EXP:
				getLogExp().clear();
				getLogExp().addAll((Collection<? extends ExpresionLogica>)newValue);
				return;
			case PagosPackage.IF_CONDITION__FORMULA_RETURN:
				setFormulaReturn((ReturnBlock)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case PagosPackage.IF_CONDITION__LOG_EXP:
				getLogExp().clear();
				return;
			case PagosPackage.IF_CONDITION__FORMULA_RETURN:
				setFormulaReturn((ReturnBlock)null);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case PagosPackage.IF_CONDITION__LOG_EXP:
				return logExp != null && !logExp.isEmpty();
			case PagosPackage.IF_CONDITION__FORMULA_RETURN:
				return formulaReturn != null;
		}
		return super.eIsSet(featureID);
	}

} //IfConditionImpl
