/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos.impl;

import co.edu.uniandes.pagos.BusinessAttribute;
import co.edu.uniandes.pagos.PagosPackage;
import co.edu.uniandes.pagos.TerminalValue;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminal Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.pagos.impl.TerminalValueImpl#getParent <em>Parent</em>}</li>
 *   <li>{@link co.edu.uniandes.pagos.impl.TerminalValueImpl#getVariable <em>Variable</em>}</li>
 *   <li>{@link co.edu.uniandes.pagos.impl.TerminalValueImpl#getMethod <em>Method</em>}</li>
 *   <li>{@link co.edu.uniandes.pagos.impl.TerminalValueImpl#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TerminalValueImpl extends ExpressionImpl implements TerminalValue
{
  /**
	 * The cached value of the '{@link #getParent() <em>Parent</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getParent()
	 * @generated
	 * @ordered
	 */
  protected EObject parent;

  /**
	 * The cached value of the '{@link #getVariable() <em>Variable</em>}' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getVariable()
	 * @generated
	 * @ordered
	 */
  protected BusinessAttribute variable;

  /**
	 * The default value of the '{@link #getMethod() <em>Method</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getMethod()
	 * @generated
	 * @ordered
	 */
  protected static final String METHOD_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getMethod() <em>Method</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getMethod()
	 * @generated
	 * @ordered
	 */
  protected String method = METHOD_EDEFAULT;

  /**
	 * The default value of the '{@link #getValor() <em>Valor</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getValor()
	 * @generated
	 * @ordered
	 */
  protected static final String VALOR_EDEFAULT = null;

  /**
	 * The cached value of the '{@link #getValor() <em>Valor</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getValor()
	 * @generated
	 * @ordered
	 */
  protected String valor = VALOR_EDEFAULT;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected TerminalValueImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return PagosPackage.Literals.TERMINAL_VALUE;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EObject getParent()
  {
		if (parent != null && parent.eIsProxy()) {
			InternalEObject oldParent = (InternalEObject)parent;
			parent = eResolveProxy(oldParent);
			if (parent != oldParent) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, PagosPackage.TERMINAL_VALUE__PARENT, oldParent, parent));
			}
		}
		return parent;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EObject basicGetParent()
  {
		return parent;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setParent(EObject newParent)
  {
		EObject oldParent = parent;
		parent = newParent;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, PagosPackage.TERMINAL_VALUE__PARENT, oldParent, parent));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public BusinessAttribute getVariable()
  {
		if (variable != null && variable.eIsProxy()) {
			InternalEObject oldVariable = (InternalEObject)variable;
			variable = (BusinessAttribute)eResolveProxy(oldVariable);
			if (variable != oldVariable) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, PagosPackage.TERMINAL_VALUE__VARIABLE, oldVariable, variable));
			}
		}
		return variable;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public BusinessAttribute basicGetVariable()
  {
		return variable;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setVariable(BusinessAttribute newVariable)
  {
		BusinessAttribute oldVariable = variable;
		variable = newVariable;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, PagosPackage.TERMINAL_VALUE__VARIABLE, oldVariable, variable));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public String getMethod()
  {
		return method;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setMethod(String newMethod)
  {
		String oldMethod = method;
		method = newMethod;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, PagosPackage.TERMINAL_VALUE__METHOD, oldMethod, method));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public String getValor()
  {
		return valor;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setValor(String newValor)
  {
		String oldValor = valor;
		valor = newValor;
		if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, PagosPackage.TERMINAL_VALUE__VALOR, oldValor, valor));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case PagosPackage.TERMINAL_VALUE__PARENT:
				if (resolve) return getParent();
				return basicGetParent();
			case PagosPackage.TERMINAL_VALUE__VARIABLE:
				if (resolve) return getVariable();
				return basicGetVariable();
			case PagosPackage.TERMINAL_VALUE__METHOD:
				return getMethod();
			case PagosPackage.TERMINAL_VALUE__VALOR:
				return getValor();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case PagosPackage.TERMINAL_VALUE__PARENT:
				setParent((EObject)newValue);
				return;
			case PagosPackage.TERMINAL_VALUE__VARIABLE:
				setVariable((BusinessAttribute)newValue);
				return;
			case PagosPackage.TERMINAL_VALUE__METHOD:
				setMethod((String)newValue);
				return;
			case PagosPackage.TERMINAL_VALUE__VALOR:
				setValor((String)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case PagosPackage.TERMINAL_VALUE__PARENT:
				setParent((EObject)null);
				return;
			case PagosPackage.TERMINAL_VALUE__VARIABLE:
				setVariable((BusinessAttribute)null);
				return;
			case PagosPackage.TERMINAL_VALUE__METHOD:
				setMethod(METHOD_EDEFAULT);
				return;
			case PagosPackage.TERMINAL_VALUE__VALOR:
				setValor(VALOR_EDEFAULT);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case PagosPackage.TERMINAL_VALUE__PARENT:
				return parent != null;
			case PagosPackage.TERMINAL_VALUE__VARIABLE:
				return variable != null;
			case PagosPackage.TERMINAL_VALUE__METHOD:
				return METHOD_EDEFAULT == null ? method != null : !METHOD_EDEFAULT.equals(method);
			case PagosPackage.TERMINAL_VALUE__VALOR:
				return VALOR_EDEFAULT == null ? valor != null : !VALOR_EDEFAULT.equals(valor);
		}
		return super.eIsSet(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String toString()
  {
		if (eIsProxy()) return super.toString();

		StringBuffer result = new StringBuffer(super.toString());
		result.append(" (method: ");
		result.append(method);
		result.append(", valor: ");
		result.append(valor);
		result.append(')');
		return result.toString();
	}

} //TerminalValueImpl
