/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.pagos;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Application</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.pagos.Application#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.pagos.Application#getIntermediary <em>Intermediary</em>}</li>
 * </ul>
 *
 * @see co.edu.uniandes.pagos.PagosPackage#getApplication()
 * @model
 * @generated
 */
public interface Application extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see co.edu.uniandes.pagos.PagosPackage#getApplication_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link co.edu.uniandes.pagos.Application#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Intermediary</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Intermediary</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Intermediary</em>' containment reference.
	 * @see #setIntermediary(Intermediary)
	 * @see co.edu.uniandes.pagos.PagosPackage#getApplication_Intermediary()
	 * @model containment="true"
	 * @generated
	 */
  Intermediary getIntermediary();

  /**
	 * Sets the value of the '{@link co.edu.uniandes.pagos.Application#getIntermediary <em>Intermediary</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Intermediary</em>' containment reference.
	 * @see #getIntermediary()
	 * @generated
	 */
  void setIntermediary(Intermediary value);

} // Application
