/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.parser.antlr;

import co.edu.uniandes.parser.antlr.internal.InternalPagosParser;
import co.edu.uniandes.services.PagosGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PagosParser extends AbstractAntlrParser {

	@Inject
	private PagosGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPagosParser createParser(XtextTokenStream stream) {
		return new InternalPagosParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Application";
	}

	public PagosGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PagosGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
