/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes;

import co.edu.uniandes.PagosStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PagosStandaloneSetup extends PagosStandaloneSetupGenerated {
  public static void doSetup() {
    PagosStandaloneSetup _pagosStandaloneSetup = new PagosStandaloneSetup();
    _pagosStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
