/**
 *
 * $Id$
 */
package PaymentsApp.validation;

import PaymentsApp.BusinessAttributeCollection;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link PaymentsApp.DataForm}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataFormValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSuperEntityAttributes(EList<BusinessAttributeCollection> value);

	boolean validateBusinessFields(EList<BusinessAttributeCollection> value);
}
