/**
 *
 * $Id$
 */
package PaymentsApp.validation;

import PaymentsApp.BusinessAttribute;
import PaymentsApp.CalculationTemplate;
import PaymentsApp.Provider;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link PaymentsApp.InformationTemplate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InformationTemplateValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateAttLists(EList<BusinessAttribute> value);
	boolean validateTemplates(EList<CalculationTemplate> value);
	boolean validateProviders(EList<Provider> value);
}
