/**
 *
 * $Id$
 */
package PaymentsApp.validation;

import PaymentsApp.BusinessAttributeCollection;
import PaymentsApp.BusinessValue;
import PaymentsApp.DataForm;
import PaymentsApp.SuperEntity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link PaymentsApp.Intermediary}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermediaryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSuperentities(EList<SuperEntity> value);
	boolean validateBusinessValue(BusinessValue value);

	boolean validateIntermediaryAttributes(EList<BusinessAttributeCollection> value);

	boolean validateTemplates(EList<DataForm> value);
}
