/**
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.ui.AbstractPagosUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PagosUiModule extends AbstractPagosUiModule {
  public PagosUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
