/**
 *
 * $Id$
 */
package co.edu.uniandes.pagos.validation;

import co.edu.uniandes.pagos.ExpresionLogica;
import co.edu.uniandes.pagos.TerminalValue;

/**
 * A sample validator interface for {@link co.edu.uniandes.pagos.ExpresionLogica}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExpresionLogicaValidator {
	boolean validate();

	boolean validateVariable(TerminalValue value);
	boolean validateLogOper(String value);
	boolean validateVariable2(TerminalValue value);
	boolean validateLiteral(String value);
	boolean validateConOper(String value);
	boolean validateExp(ExpresionLogica value);
}
