/**
 *
 * $Id$
 */
package co.edu.uniandes.pagos.validation;

import co.edu.uniandes.pagos.ExpresionLogica;
import co.edu.uniandes.pagos.ReturnBlock;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link co.edu.uniandes.pagos.IfCondition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfConditionValidator {
	boolean validate();

	boolean validateLogExp(EList<ExpresionLogica> value);
	boolean validateFormulaReturn(ReturnBlock value);
}
