/**
 *
 * $Id$
 */
package co.edu.uniandes.pagos.validation;

import co.edu.uniandes.pagos.BusinessAttribute;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link co.edu.uniandes.pagos.TerminalValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TerminalValueValidator {
	boolean validate();

	boolean validateParent(EObject value);
	boolean validateVariable(BusinessAttribute value);
	boolean validateMethod(String value);
	boolean validateValor(String value);
}
