/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui.tests;

import co.edu.uniandes.gramaticaPayments.ui.internal.GramaticaPaymentsActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class PagosUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GramaticaPaymentsActivator.getInstance().getInjector("co.edu.uniandes.Pagos");
	}

}
